[build]
  # Tells Netlify where your static HTML/JS files are
  publish = "." 
  # Tells Netlify where your Serverless Functions are
  functions = "netlify/functions"

# This creates a 'friendly' API path:
# A request to /api/posts will be sent to the netlify/functions/get-posts.js function
[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/get-posts"
  status = 200
  
  # ... existing content ...

[[redirects]]
  from = "/api/posts" # Use the base path for POST (Create New)
  to = "/.netlify/functions/create-post"
  status = 200
  force = true
