[build]
  # Tells Netlify where your static HTML/JS files are
  publish = "." 
  # Tells Netlify where your Serverless Functions are
  functions = "netlify/functions"

# Redirects all requests to /api/posts/* and /api/posts to the single posts.js function.
# This allows the posts.js function to handle GET, POST, PUT, and DELETE.
[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/posts"
  status = 200
  force = true

[[redirects]]
  from = "/api/posts"
  to = "/.netlify/functions/posts"
  status = 200
  force = true

