[build]
  # Tells Netlify where your static HTML/JS files are
  publish = "." 
  # Tells Netlify where your Serverless Functions are
  functions = "netlify/functions"

# Redirect for the consolidated 'posts' CRUD function
[[redirects]]
  from = "/api/posts/*"
  to = "/.netlify/functions/posts"
  status = 200

# New redirect for the 'interactions' CRUD function
[[redirects]]
  from = "/api/interactions/*"
  to = "/.netlify/functions/interactions"
  status = 200